spring:
  application:
    name: service-user
  redis:
    host: beatmoney.com
    port: 6379
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/xinguan?useSSL=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 1
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: SELECT 1
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations:  classpath*:/mapper/*.xml
server:
  port: 8001